### ISSUE TITLE
[Kotlin 2.3.0] Js/WasmJs PlatformTools to use `qualifiedName` (instead of `simpleName`)

### ISSUE THREAD

**Issue by zombiehub** [Ekito/koin#2312]
**Describe the bug**
Please switch to `qualifiedName` on Js/WasmJs -- since using simple class name clobbers bean definitions (and trips up `allowOverrides = false`), causing catastrophic failures in Browser vs Mobile/Desktop.

It looks like Kotlin 2.3 will have `-Xwasm-kclass-fqn` by default. See https://youtrack.jetbrains.com/issue/KT-69621/K-Wasm-Consider-enabling-support-for-KClass.qualifiedName-by-default

Thanks.

**Comment by arnaudgiuliani** [comment]
Yes, 2.3 will be part of Koin 4.2

**Comment by arnaudgiuliani** [comment]
Fixed in 4.2 beta3

**Comment by zombiehub** [comment]
Sorry, spoke too soon. Seems like the problem persists... I get:

```
(Koin) (+) override index 'InAuthScope::_auth_' -> '[Scoped: 'InAuthScope',scope:_auth_]'
```

indicating that short names are still being used. And of course, the web crashes afterwards because the type will be wrong.

**Comment by arnaudgiuliani** [comment]
let's check that 👍

**Comment by arnaudgiuliani** [comment]
Status: the fix for **WasmJs** is a one-liner — `KoinPlatformTools.getClassName` should prefer `qualifiedName` (now available on WasmJs since Kotlin 2.3.0) over `simpleName`, so same-simple-name classes stop colliding on the type index key. Verified locally: with two same-simple-name classes a request returned the wrong type (`ClassCastException`) before, and resolves correctly after.

**Holding it until it can ship with a regression test**, which is currently blocked:
- **Kotlin/JS can't be fixed the same way** — `KClass.qualifiedName` is a *compile error* on JS ("This reflection API is not supported in Kotlin/JS"), so JS keeps `simpleName`. A `commonTest` test therefore fails on the JS target.
- A **WasmJs-only test source set crashes the Kotlin/Wasm compiler** (`ArrayIndexOutOfBoundsException` in `compileTestKotlinWasmJs`), and koin-core has no per-target test source sets.

Moving to **4.3.0**: ship the WasmJs fix once there's a viable regression-test path (resolve the wasmJsTest compiler crash, or a Kotlin version that fixes it). JS remains limited by upstream (no `qualifiedName`).
