### ISSUE TITLE
StrictMode violation in Application.onCreate on Android

### ISSUE THREAD

**Issue by mattmook** [Ekito/koin#96]
With StrictMode enabled on Android, Koin v0.9.1 causes a violation due to disk access when initialised from the main thread in `Application.onCreate`. This is caused by the access to `ClassLoader.getResources` in `bindKoinProperties`.

```
03-29 22:03:25.213 27304-27304/? D/StrictMode: StrictMode policy violation; ~duration=80 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=196671 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:837)
        at dalvik.system.DexPathList$Element.maybeInit(DexPathList.java:649)
        at dalvik.system.DexPathList$Element.findResource(DexPathList.java:682)
        at dalvik.system.DexPathList.findResource(DexPathList.java:488)
        at dalvik.system.BaseDexClassLoader.findResource(BaseDexClassLoader.java:144)
        at java.lang.ClassLoader.getResource(ClassLoader.java:793)
        at java.lang.Class.getResource(Class.java:2255)
        at org.koin.Koin.bindKoinProperties(Koin.kt:31)
        at org.koin.Koin.bindKoinProperties$default(Koin.kt:30)
        at org.koin.standalone.StandAloneContext.loadProperties(StandAloneContext.kt:77)
        at org.koin.standalone.StandAloneContext.startKoin(StandAloneContext.kt:101)
        at org.koin.standalone.StandAloneContext.startKoin$default(StandAloneContext.kt:95)
        at com.appmattus.aisfor.Application.onCreate(Application.kt:25)
```

StrictMode enabled with the following:

    StrictMode.setThreadPolicy(
        StrictMode.ThreadPolicy.Builder()
            .detectAll()
            .penaltyLog()
            .penaltyDialog()
            .build()
    )

Could a property be added to`startKoin` to disable this initialisation by default as in most instances I assume this file won't exist so the attempted loading would be unnecessary?

**Comment by arnaudgiuliani** [comment]
Fixed for 0.9.2. Please check the `0.9.2-alpha-3`.

**Comment by mattmook** [comment]
I'm still seeing the same issue with `0.9.2-alpha-3`:

  04-06 21:50:19.740 4378-4378/com.appmattus.aisfor D/StrictMode: StrictMode policy violation; ~duration=81 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=196639 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:240)
        at java.io.File.isDirectory(File.java:804)
        at java.io.File.toURI(File.java:698)
        at libcore.io.ClassPathURLStreamHandler.<init>(ClassPathURLStreamHandler.java:52)
        at dalvik.system.DexPathList$Element.maybeInit(DexPathList.java:532)
        at dalvik.system.DexPathList$Element.findResource(DexPathList.java:568)
        at dalvik.system.DexPathList.findResource(DexPathList.java:440)
        at dalvik.system.BaseDexClassLoader.findResource(BaseDexClassLoader.java:74)
        at java.lang.ClassLoader.getResource(ClassLoader.java:793)
        at java.lang.Class.getResource(Class.java:2139)
        at org.koin.Koin.bindKoinProperties(Koin.kt:31)
        at org.koin.Koin.bindKoinProperties$default(Koin.kt:30)
        at org.koin.standalone.StandAloneContext.loadProperties(StandAloneContext.kt:91)
        at org.koin.standalone.StandAloneContext.startKoin(StandAloneContext.kt:119)
        at org.koin.standalone.StandAloneContext.startKoin$default(StandAloneContext.kt:112)
        at com.appmattus.aisfor.Application.onCreate(Application.kt:25)

**Comment by arnaudgiuliani** [comment]
did you disable the Koin properties loading from assets with `loadProperties` to false?

**Comment by mattmook** [comment]
Hmm no, although I don't see a loadProperties in the alpha or in the branch `0.9.2` source, am I missing something? 

So, at the moment I'm starting Koin with the following in my Application class:

    override fun onCreate() {
        super.onCreate()

        enableStrictMode()

        startKoin(
            listOf(
                appContextModule(this),
                frescoModule()
            )
        ) with this
    }

**Comment by arnaudgiuliani** [comment]
replace your startKoin code with the Android start version: 

```kotlin
startKoin(
    this,
    listOf(
            appContextModule(this),
            frescoModule()
        ),
    loadProperties = false
)
```

**Comment by mattmook** [comment]
I've changed my code as above however that doesn't make a difference because the issue is caused by the attempt to load `koin.properties` within the `StandAloneContext`.

**Comment by arnaudgiuliani** [comment]
Ok. I'll check that.

**Comment by arnaudgiuliani** [comment]
Ok. Fixed in `0.9.2-alpha-5`

**Comment by mattmook** [comment]
Thanks, works like a charm
